name: Build and Upload Artifacts

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: 构建项目
        run: |
          if [ -f ./mvnw ]; then
            ./mvnw clean package -DskipTests
          else
            mvn clean package -DskipTests
          fi

      - name: 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: geyserskinmanager-artifacts
          path: |
            **/target/*.jar 